version: "3"

services:
  postgres: # (*1)
    image: postgres:13-alpine
    container_name: go-twitter-clone-postgres
    ports:
      - 15432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  pg_data:
# (*1) psql を使って接続可能
# $ docker-compose run --rm postgres psql -h go-twitter-clone-postgres -U postgres
