// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	ScreenID   string `json:"screen_id"`
	ScreenName string `json:"screen_name"`
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	ScreenID   string `json:"screen_id"`
	ScreenName string `json:"screen_name"`
}
